# Generated by Django 5.1.3 on 2024-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0002_pointcloudfile_delete_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointcloudfile",
            name="file",
            field=models.FileField(upload_to="dashboardapp/"),
        ),
    ]
