# Generated by Django 5.1.3 on 2025-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboardapp", "0003_alter_pointcloudfile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file_name", models.CharField(max_length=255)),
                ("table_index", models.IntegerField()),
                ("table_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="PointCloudFile",
        ),
    ]
